server:
   port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms?useUnicode=true&characterEncoding=utf-8&useSSL=false&severTimezone=GM%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jjkbts1230
logging:
  level:
    com.example.wms.mapper: debug
